# Generated by Django 2.2.2 on 2019-07-01 08:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
