# Generated by Django 2.2.2 on 2019-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0002_book_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
