# Generated by Django 2.2.2 on 2019-07-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0004_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
