# Generated by Django 2.2.2 on 2019-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0005_auto_20190701_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_clean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
