# Generated by Django 2.2.2 on 2019-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_db', '0006_book_isbn_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
